import asyncio
import random

async def process_request(message: str):
    """
    Analyzes the user's message and routes it to the appropriate model (Fast vs. Thinking).
    """
    message_lower = message.lower()
    
    # Simple keyword-based routing logic
    thinking_keywords = ["analyze", "trend", "predict", "complex", "why", "reason", "plan"]
    
    is_thinking_task = any(keyword in message_lower for keyword in thinking_keywords)
    
    if is_thinking_task:
        return await handle_thinking_model(message)
    else:
        return handle_fast_model(message)

def handle_fast_model(message: str):
    """
    Simulates a fast, direct response.
    """
    # Mock responses for demonstration
    if "sum" in message.lower():
        content = "The formula for sum is =SUM(A1:A10)."
    elif "average" in message.lower():
        content = "The formula for average is =AVERAGE(A1:A10)."
    elif "help" in message.lower():
        content = "I can help you with Excel formulas and data analysis. Just ask!"
    else:
        content = "I'm a fast model. I can give you quick formulas. For deep analysis, ask me to 'analyze' something."

    return {
        "response": content,
        "model_used": "fast"
    }

async def handle_thinking_model(message: str):
    """
    Simulates a thinking model with a processing delay.
    """
    # Simulate "thinking" time
    await asyncio.sleep(2.5) 
    
    # Mock analysis response
    content = (
        "**Analysis Report**\n\n"
        "1. **Trend Identification**: The data shows a steady increase over the last quarter.\n"
        "2. **Outliers**: No significant outliers detected in the provided range.\n"
        "3. **Recommendation**: Consider using a forecast sheet to predict next month's values.\n\n"
        "*Generated by Thinking Model*"
    )
    
    return {
        "response": content,
        "model_used": "thinking"
    }
